### ISSUE TITLE
edit reviews

### ISSUE THREAD

**Issue by sjorsvanheuveln** [bolcom/bolcom.github.io#1]
Hey dudes.

Ik kan de juiste repo niet vinden. Maar bol heeft een edit button voor reviews nodig. Super irri dat het er niet is.
Time to fix it!

**Comment by ewjmulder** [comment]
Hi @sjorsvanheuveln thanks for your comment. What exactly do you mean? Which repo are you looking for? Ah wait, are you trying to find the web shop code here to create an issue for edit review functionality? It would be very cool if that repo was open source but nope it is not. Nevertheless, I will forward your request to the web shop team. It could very well be though that it's on purpose that review editing is not possible, to prevent people changing their review under pressure.

**Comment by sjorsvanheuveln** [comment]
Please forward. The current editing experience is really s*, bc it's non-existent. Amazon has it though.
Perhaps add a recommendation that they could allow editing within 1 day or 1h after posting a review.
Bc now one has to request a manual delete if there's a spelling mistake.
